### ISSUE TITLE
在 metamask 上查看不到自己的 Finger 币

### ISSUE THREAD

**Issue by Suomea** [fingerchar/fingernft#1]
## 我的钱包地址
0x670e7Eeeb51C79a4Fa23189964b6D47fB8f4AcE2

## 问题
我在 metamask 上已导入了token: 0x0c5be767fe4d46f87b0263e9e171ac3388b6343f，但是在 rinkeby 网络下 Finger 币仍然显示为 0。交易记录了：https://rinkeby.etherscan.io/address/0x670e7eeeb51c79a4fa23189964b6d47fb8f4ace2#tokentxns

结果如图
![image](https://user-images.githubusercontent.com/26758537/143983605-8a37ae88-251d-4180-a0aa-86fca911770a.png)

**Comment by fingerchar** [comment]
你填的finger币地址错了 0xd36b397202af64bbb651c0fde0472c2d4908439e 应该是这个 https://rinkeby.etherscan.io/token/0xd36b397202af64bbb651c0fde0472c2d4908439e

**Comment by Suomea** [comment]
> 0xd36b397202af64bbb651c0fde0472c2d4908439e

是的，谢啦！

**Comment by minikiller** [comment]
@Suomea 请问你是如何给自己增加的100Finger币呢？ 我是一个初学者，多谢你了。

**Comment by Suomea** [comment]
> @Suomea 请问你是如何给自己增加的100Finger币呢？ 我是一个初学者，多谢你了。

没法给自己加，需要别人转给你。
