### ISSUE TITLE
FINGERNFT后台管理系统只有后端代码，为啥没有前端代码。

### ISSUE THREAD

**Issue by tanier53** [fingerchar/fingernft#10]
1.目前市场代码前后端是有的，但没有初始化数据，前端会渲染失败；
2.接着上一个问题，如果没有初始化数据，起码应该有后台管理系统页前端页面才行，不然怎么配置初始化数据，现在只能靠看代码模拟数据来初始化系统。

**Comment by fingerchar** [comment]
https://github.com/fingerchar/fingernft/tree/main/vue-admin
