### ISSUE TITLE
need support initial test data

### ISSUE THREAD

**Issue by RenYang99431** [fingerchar/fingernft#13]
api server need run with data, but no initial data in project.
suppose provide initial data will help many developers.

good proj
thx for share.

**Comment by fingerchar** [comment]
we just pushed a version, you can pull it down and have a look

**Comment by dongphuongman** [comment]
> we just pushed a version, you can pull it down and have a look

Could you provide password login bro.

**Comment by fingerchar** [comment]
admin  12345678

**Comment by fingerchar** [comment]
> > we just pushed a version, you can pull it down and have a look
> 
> Could you provide password login bro.

admin 12345678

**Comment by RenYang99431** [comment]
Well done,
It seems a complete & complex project, thx for share.
