### ISSUE TITLE
请问 BuyerFeeSigner私钥是什么

### ISSUE THREAD

**Issue by TracyH1988** [fingerchar/fingernft#18]
请问BuyerFeeSigner私钥是指哪个账户的私钥？合约部署的那个账户还是购买方的账户？因为交易报错：
Transaction: 0x8f7ae5874aff89d0b65862c513ad8870d422a4bfe52bfd622c32c69ec0f20c36 exited with an error (status 0). Please check that the transaction: - satisfies all conditions set by Solidity `require` statements. - does not trigger a Solidity `revert` statement.

![image](https://user-images.githubusercontent.com/13996290/146120923-fff4213b-a66c-44b6-bcaa-37356662197f.png)
看上去是签名报错引起的，所以是私钥不对？应该用哪个私钥 配置到 BuyerFeeSigner 里呢？

**Comment by TracyH1988** [comment]
这样部署出来，没有办法完成链上交易

**Comment by fingerchar** [comment]
你在部署nftexchange合约时，传入BuyerFeeSigner参数的私钥
