### ISSUE TITLE
Error when complie

### ISSUE THREAD

**Issue by dongphuongman** [fingerchar/fingernft#2]
[ERROR] Failed to execute goal on project fingernft-api: Could not resolve dependencies for project com.fingerchar:fingernft-api:jar:0.1.0: Could not find artifact com.fingerchar:fingerchar-encry:jar:0.1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

How can i fix these error

**Comment by fingerchar** [comment]
缺少jar包原因  文件我已经传上去了 重新pull试试

**Comment by dongphuongman** [comment]
> I have uploaded the file because of the lack of jar package and try to pull again.
Got it, thank you
