### ISSUE TITLE
合约部署

### ISSUE THREAD

**Issue by nameToJune** [fingerchar/fingernft#24]
安装手册中，合约部署配置如下：
config.js如下:
module.exports = {
  privateKey: "",	// 表示私钥
  apiUrl: "https://rinkeby.infura.io/v3/{token}",	// rinkeby的rpc
  chainId: 4,	// rinkeby 的network id
  NFTName: "FingerNFT",		// nft合约名称
  miner: "0x974423356ba75b1aaf24bbec7c8cc8cf0678554f", // 铸造nft时，授权的钱包地址
  beneficiary: "0x79aca18162577437cc763e36df07bac6938b0b69", // 收取手续费钱包地址
  buyerFeeSigner: "0x364beb2672323691088d9055518b2f750d82eee5",	// 交易授权签名
}
请问，buyerFeeSigner 这个参数从哪里来，meta钱包好像没法导出这个参数，但是看合约代码，这个参数好像就是一个地址。。能否告知一下

**Comment by fingerchar** [comment]
buyerFeeSigner 也是个钱包地址  
miner 、beneficiary、buyerFeeSigner这三个都是钱包地址，其中miner, buyerFeeSigner这两个钱包地址的私钥 要在后台配置
beneficiary这个钱包是用来收手续费的，私钥不要泄露出去
miner, beneficiary, buyerFeeSigner在合约里都有设置的接口 如果他们私钥泄露出去，你可以修改成其他钱包地址

**Comment by nameToJune** [comment]
好的，谢谢
![image](https://user-images.githubusercontent.com/32387174/150084390-f69a549c-6984-4279-9a6f-7ad4ff8ed31b.png)

请问提示我们账号已经有这个role了的错误，是否是因为配置项中的某项地址已经被用过了，我看到Role合约中有add/remove等方法，能否具体告诉一下是那个配置地址用过了，，，因为我基础问题，我短时间没法调用remove方法，只能换地址了

**Comment by fingerchar** [comment]
#25

**Comment by tanqiyou1990** [comment]
> buyerFeeSigner 也是个钱包地址 miner 、beneficiary、buyerFeeSigner这三个都是钱包地址，其中miner, buyerFeeSigner这两个钱包地址的私钥 要在后台配置 beneficiary这个钱包是用来收手续费的，私钥不要泄露出去 miner, beneficiary, buyerFeeSigner在合约里都有设置的接口 如果他们私钥泄露出去，你可以修改成其他钱包地址

buyerFeeSigner这个地址的作用是什么？
