### ISSUE TITLE
合约部署

### ISSUE THREAD

**Issue by nameToJune** [fingerchar/fingernft#25]
你好，请问部署合约出现这下面2种错误是什么导致的，如何解决

![image](https://user-images.githubusercontent.com/32387174/150090016-8a34ad66-7be4-4c2a-ab51-5ff93fd36ada.png)

切换到测试链之后

![image](https://user-images.githubusercontent.com/32387174/150089989-16d223e3-1217-4a89-9ee9-e2673655c384.png)

**Comment by fingerchar** [comment]
这是因为你重复执行了`node operator.js` 
这个脚本是添加角色，添加完后，就不用再添加了

**Comment by nameToJune** [comment]
那我现在应该怎么处理，执行完 node  deploy.js后报的上述2个错误，都没还到operator.js 的执行，仓库本身有一个json文件，0x2b5a2bdb6ca33b73a8f84546914ea5d42843fdbf_4.json  这个应该删除吧，让大家自己生成，现在我是无法生成这个json

**Comment by fingerchar** [comment]
不用执行了  你这个肯定是已经执行过

**Comment by fingerchar** [comment]
对的 把它删了  这个是我们演示版的 你要删掉 部署你自己的合约

**Comment by nameToJune** [comment]
重新准备了新的环境，按照INSTALL.md手册进行按照，执行到脚本node deploy.js（nft-contract/scripts/deploy.js） 时，仍然是下图的错误
![image](https://user-images.githubusercontent.com/32387174/150136685-6284ff56-58cd-4a35-8a66-f885aaeeda0c.png)
也没有生成相应的json文件，这种情况是什么导致的呢
install.md截图部分如下（红线部分）
![image](https://user-images.githubusercontent.com/32387174/150137291-361af1d1-6952-42a6-8912-991de08a48fb.png)
其中红线部分 migrations目录有合约分别部署的脚本，而我执行的脚本在scripts目录下，我现在应该怎么排除问题

**Comment by nameToJune** [comment]
成功
