### ISSUE TITLE
 node deploy.js  无法部署NFT721

### ISSUE THREAD

**Issue by nameToJune** [fingerchar/fingernft#29]
rinkeby环境、以及自己的测试链、新建的地址账户都无法部署成功
切换了不同的环境，但都报同样的错误，
打印日志如下：
[root@localhost scripts]# node deploy.js 
data {}
start deploying...
create NFT721...
create NFT721 error execution reverted: Roles: account already has role
0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001f526f6c65733a206163636f756e7420616c72656164792068617320726f6c6500

**Comment by fingerchar** [comment]
config.js里的miner地址 不能跟部署钱包地址一样

**Comment by nameToJune** [comment]
你好，感谢回答，但是没能理解，可否描述详细一些

**Comment by nameToJune** [comment]
我现在理解了，，部署合约的地址（私钥）不能跟miner地址重复
