### ISSUE TITLE
 IPFS在哪安装

### ISSUE THREAD

**Issue by jidechen** [fingerchar/fingernft#3]
我的电脑是windows系统，我装了宝塔Windows面板，请问下，安装步骤里的IPFS是在哪里安装呢？

**Comment by fingerchar** [comment]
wget https://dist.ipfs.io/go-ipfs/v0.9.1/go-ipfs_v0.9.1_linux-amd64.tar.gz
tar –zxvf go-ipfs_v0.9.1_linux-amd64.tar.gz
// 或者分两步
gunzip go-ipfs_v0.9.1_linux-amd64.tar.gz
tar –xvf go-ipfs_v0.9.1_linux-amd64.tar
cd go-ipfs
sh install.sh

**Comment by fingerchar** [comment]
[INSTALL.md](https://github.com/fingerchar/fingernft/blob/main/INSTALL.md)
这个文件里有讲解
