### ISSUE TITLE
unlogin error 

### ISSUE THREAD

**Issue by nameToJune** [fingerchar/fingernft#35]
![image](https://user-images.githubusercontent.com/32387174/155302461-2cb0c9a5-bf20-41c2-8e73-fbc79faadf74.png)

部署后，连接的是测试私链。发现钱包调用弹出签名确认，确认后，仍然无法创建NFT。请问是什么原因导致的，多次尝试（包括清除缓存，重新部署本地链）

**Comment by fingerchar** [comment]
确认后 继续点击 也能不行吗？

**Comment by nameToJune** [comment]
不行。。。清空数据库后仍然不行，找了个新环境重装正常。。

**Comment by Ximcxccc** [comment]
可以留一下联系方式吗

**Comment by nameToJune** [comment]
> 可以留一下联系方式吗

？
