### ISSUE TITLE
缺失重要代码

### ISSUE THREAD

**Issue by tanier53** [fingerchar/fingernft#4]
fingger-api工程下面缺乏：1.com.fingerchar.api.utils.DappCryptoUtil，2.com.fingerchar.api.vo.SignOrderInfo
   poms文件里面:没有找到fingerchar-encry这个工程

**Comment by fingerchar** [comment]
https://github.com/fingerchar/fingernft/blob/main/nft-api/fingernft-api/dependency/fingerchar-encry-0.1.0.jar
