### ISSUE TITLE
"execution reverted: owner should sign tokenId"

### ISSUE THREAD

**Issue by heheiscool** [fingerchar/fingernft#41]
![image](https://user-images.githubusercontent.com/30858541/157084283-11bc5b56-7ed0-4e14-add9-f3558d10dd74.png)
mint后报错，"execution reverted: owner should sign tokenId"
![image](https://user-images.githubusercontent.com/30858541/157084720-7ae1c705-37c9-43f2-92fb-998a426fe20b.png)
请教求解

**Comment by fingerchar** [comment]
这是签名的错误 nft mint的时候 需要拿到这个nft miner的签名 才能铸造
部署合约的时候 config.js里面有个miner 这个地址的私钥设置到后台配置里

**Comment by floodboad** [comment]
> 

@fingerchar 这个miner 钱包地址有什么特殊要求吗，任意生成的一个钱包地址都可以吗？
