### ISSUE TITLE
Interested to buy standard version and install.

### ISSUE THREAD

**Issue by midoelmelegy** [fingerchar/fingernft#59]
Good day  there, great job on the work. I'm Interested in buying the nft marketplace standard edition licence and want to ask do you offer installation  on my server? Looking for help installing it can you please contact me on tomcatcity.god@gmail.com 

I have tested it and it had some bugs but today I see most of the bugs are gone. So I would like to know if you can help with installation on my ubuntu server.

**Comment by midoelmelegy** [comment]
Tried calling your number but no answer.

**Comment by fingerchar** [comment]
Hello, sorry to reply you so late, our customer service has contacted
