### ISSUE TITLE
Error when complie nft-pc

### ISSUE THREAD

**Issue by dongphuongman** [fingerchar/fingernft#6]
When complie nft-pc  by  npm i  
Error 
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path C:\Development\BlockChain\fingernft\nft-pc\node_modules\gulp-sass\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Development\BlockChain\fingernft\nft-pc\node_modules\gulp-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [

**Comment by fingerchar** [comment]
我推了新版本上去  你试试还会不会这样
命令是

```
yarn
yarn serve
```
