### ISSUE TITLE
api初始化密钥数据报错，请问配置中的三个参数  keyPath:      rsaPriKey:      rsaPubKey: 分别是啥

### ISSUE THREAD

**Issue by 2-huo** [fingerchar/fingernft#7]
![image](https://user-images.githubusercontent.com/33863671/145173201-4519bddb-ec7f-4547-9c26-6d3d000a6156.png)
![image](https://user-images.githubusercontent.com/33863671/145173413-fbfca008-d8fe-45b2-be0c-abc8cafec799.png)

**Comment by chencrk** [comment]
keyPath代表 保存经过rsa加密后数据的文件的路径

**Comment by chencrk** [comment]
rsaPriKey和rsaPubKey对应就是rsa256的公钥私钥。  私钥加密，公钥解密

**Comment by fzkun** [comment]
遇到同样得问题，小白，不知道怎么输入

**Comment by fingerchar** [comment]
我们刚推了一个版本 ，已经把这个功能剔除掉了 pull下来看看
