### ISSUE TITLE
后台管理系统管理员用户能不能给一条数据，空的登录不上啊用户权限啥的，表只有结构没有数据本地进不去啊

### ISSUE THREAD

**Issue by 2-huo** [fingerchar/fingernft#8]
![image](https://user-images.githubusercontent.com/33863671/145323255-24fc4788-affa-472c-a54a-f58fbf54a9db.png)

**Comment by tanier53** [comment]
是的，不能给一条数据化数据吗？而且前台系统也是需要这些，不然怎么造数据

**Comment by minikiller** [comment]
关注这个问题。

**Comment by chencrk** [comment]
已经推了一个最新的版本上去，里面有完整的数据
