### ISSUE TITLE
FingerNFT后台管理系统的admin密码是多少？

### ISSUE THREAD

**Issue by HenryTcai** [fingerchar/fingernft#9]
![image](https://user-images.githubusercontent.com/32008347/145343634-ea3a02b6-e1e4-49af-a53a-6f84f00f395a.png)
数据库存储的是加密后的内容，那么登录的密码是什么呢？

**Comment by fingerchar** [comment]
root@123

**Comment by HenryTcai** [comment]
不是这个，这个登录不了。不过自己通过修改源码后，免密码登录（随便输入一个密码都能登录），然后再进行修改admin的密码就可以了

**Comment by tanier53** [comment]
> 

它包里面有个加密工具，你吧明文密码放进去，用main方法执行以下就可以得到加密密码 然后扔到数据库里面就OK了
